TaskManagerWeb/TaskManager/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SQLDataAccess.Repository;
using SQLDataAccess.Enteties;
using TaskManager.Models;
using System.Web.Hosting;
using TaskManager.ViewModels.UserVM;
using TaskManager.Filters;

namespace TaskManager.Controllers
{
    [AdminFilter]
    public class UserManagementController : BaseController<User, ListUserVM, CreateUserVM, EditUserVM, DeleteUserVM, UserFilterVM>
    {
        // GET: UserManagement
        public override BaseRepo<User> SetRepo()
        {
            return new UserRepo();
        }

        public override void PopulateItem(User item, CreateUserVM model)
        {
            item.Username = model.Username;
            item.Password = model.Password;
            item.IsAdmin = model.IsAdmin;
            item.Fullname = model.FullName;
            item.Email = model.Email;
        }

        public override void PopulateModel(User item, DeleteUserVM model)
        {
            model.Id = item.Id;
            model.Username = item.Username;
            model.Password = item.Password;
            model.FullName = item.Fullname;
            model.Email = item.Email;
            model.IsAdmin = item.IsAdmin;
        }

        public override void PopulateItemEdit(User item, EditUserVM model)
        {
            item.Username = model.Username;
            item.Password = model.Password;
            item.IsAdmin = model.IsAdmin;
            item.Email = model.Email;
            item.Fullname = model.FullName;
            item.Id = model.Id;

        }

        public override void PopulateModelEdit(User item, EditUserVM model)
        {
            model.Username = item.Username;
            model.Password = item.Password;
            model.FullName = item.Fullname;
            model.IsAdmin = item.IsAdmin;
            model.Email = item.Email;
            model.Id = item.Id;
        }

        public override void ExtraDelete(User user)
        {
            TaskRepo repoTask = new TaskRepo();
            LogWorkRepo repoWork = new LogWorkRepo();
            CommentRepo repoComment = new CommentRepo();

            List<Task> tasks = repoTask.GetAll(t => t.creatorId == user.Id).ToList();
            List<Comment> comments = repoComment.GetAll().ToList();
            List<LogWork> works = repoWork.GetAll().ToList();

            foreach (Task item in tasks)
            {
                foreach (Comment comment in comments)
                {
                    if (comment.taskId == item.Id)
                    {
                        repoComment.Delete(comment);
                    }
                }

                foreach (LogWork work in works)
                {
                    if (work.TaskId == item.Id)
                    {
                        repoWork.Delete(work);
                    }
                }

                repoTask.Delete(item);
            }
        }
    }
}

TaskManagerWeb/TaskManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Task Manager", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (TaskManager.Models.AuthenticationManager.LoggedUser != null)
                    {
                        if (TaskManager.Models.AuthenticationManager.LoggedUser.IsAdmin == true)
                        {
                            <li>@Html.ActionLink("User Managament", "index", "UserManagement")</li>
                            <li>@Html.ActionLink("Task Managment", "index", "TaskManagement")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Task Managment", "index", "TaskManagement")</li>
                        }
                    }

                    @if (TaskManager.Models.AuthenticationManager.LoggedUser == null)
                    {
                        <li>@Html.ActionLink("LogIn", "LogIn", "Home")</li>
                        <li>@Html.ActionLink("Register", "Create", "Home")</li>
                    }
                    else
                    {
                        string name = TaskManager.Models.AuthenticationManager.LoggedUser.Fullname;
                        <li>@Html.ActionLink("Hello " + name, "Details", "Home")</li>
                        <li>@Html.ActionLink("LogOut", "LogOut", "Home")</li>
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

TaskManagerWeb/TaskManager/Views/Shared/_Pager.cshtml
@model TaskManager.ViewModels.PagerVM

@{
    var PageSize_ChangeFunction = Model.Prefix.Replace(".", "__") + "onChange";
    var pageSizeTemplate = "/" + this.ViewContext.RouteData.Values["controller"].ToString() + "/" + this.ViewContext.RouteData.Values["action"].ToString() + "?";
    var currentPageTemplate = "/" + this.ViewContext.RouteData.Values["controller"].ToString() + "/" + this.ViewContext.RouteData.Values["action"].ToString() + "?";

    foreach (string key in this.Request.QueryString.Keys)
    {
        if (key != Model.Prefix + "PageSize" && key != Model.Prefix + "CurrentPage")
        {
            pageSizeTemplate += key + "=" + this.Request[key] + "&";
        }

        if (key != Model.Prefix + "CurrentPage")
        {
            currentPageTemplate += key + "=" + this.Request[key] + "&";
        }
    }

    foreach (var kvp in this.ViewContext.RouteData.Values)
    {
        if (kvp.Key == "controller" || kvp.Key == "action")
        {
            continue;
        }

        if (kvp.Key != Model.Prefix + "PageSize" && kvp.Key != Model.Prefix + "CurrentPage")
        {
            pageSizeTemplate += kvp.Key + "=" + this.ViewContext.RouteData.Values[kvp.Key] + "&";
        }

        if (kvp.Key != Model.Prefix + "CurrentPage")
        {
            currentPageTemplate += kvp.Key + "=" + this.ViewContext.RouteData.Values[kvp.Key] + "&";
        }
    }

    foreach (string key in this.Request.Form.Keys)
    {
        if (key != Model.Prefix + "PageSize" && key != Model.Prefix + "CurrentPage")
        {
            pageSizeTemplate += key + "=" + this.Request[key] + "&";
        }

        if (key != Model.Prefix + "CurrentPage")
        {
            currentPageTemplate += key + "=" + this.Request[key] + "&";
        }
    }
}

<script>
    function @(PageSize_ChangeFunction)() {
        var link = '@Html.Raw(pageSizeTemplate)';
        link = link + "@(Model.Prefix)PageSize=" + $("#@(Model.Prefix.Replace(".", "__"))PageSize").val();

        window.location = link;
    }
</script>
<style>
    #right {
        display: inline-block;
        float: left;
        padding: 10px;
        margin-top: 10px;
        padding-left: 0px;
    }
</style>

Page @(Model.PagesCount < Model.CurrentPage ? 0 : Model.CurrentPage) of @Model.PagesCount
<br />

<div>
<ul class="pagination">
    @for (int i = 0; i < Model.PagesCount; i++)
    {
        <li class="page-item @(Model.CurrentPage == i+1 ? "active" : "")">
            <a class="page-link" href="@(currentPageTemplate)@(Model.Prefix)CurrentPage=@(i+1)">@(i+1)</a>
        </li>
    }
</ul>

    <p id="right">
        <select class="form-control" id="@(Model.Prefix.Replace(".", "__"))PageSize" name="@(Model.Prefix)PageSize" onchange="@(PageSize_ChangeFunction)()">
            <option value="1" @(Model.PageSize == 1 ? "selected" : "")>1</option>
            <option value="5" @(Model.PageSize == 5 ? "selected" : "")>5</option>
            <option value="10" @(Model.PageSize == 10 ? "selected" : "")>10</option>
        </select>
    </p>
</div>

TaskManagerWeb/TaskManager/Views/Shared/_Search.cshtml
@model TaskManager.ViewModels.BaseFilter

@using System.Reflection;
@using TaskManager.Tools;

@{
    var filter = new Dictionary<PropertyInfo, FilterByAttribute>();
    foreach (PropertyInfo pi in Model.GetType().GetProperties())
    {
        FilterByAttribute attrib = (FilterByAttribute)pi.GetCustomAttribute(typeof(FilterByAttribute));
        if (attrib != null)
        {
            filter.Add(pi, attrib);
        }
    }

    string path = "";

    try
    {
        if (ViewContext.RouteData.Values["id"].ToString() != null)
        {
            path = "/" + ViewContext.RouteData.Values["controller"].ToString() + "/" + ViewContext.RouteData.Values["action"].ToString() + "/" + ViewContext.RouteData.Values["id"].ToString();
        }
    }
    catch (Exception)
    {
        path = "/" + ViewContext.RouteData.Values["controller"].ToString() + "/" + ViewContext.RouteData.Values["action"].ToString();
    }

}
<form action="@path" method="get">

    @foreach (string key in this.Request.QueryString.Keys)
    {
        if (!key.ToString().Contains(Model.Prefix) && key.ToString() != Model.Pager.Prefix + "CurrentPage" && key.ToString() != "id")
        {
            <input type="hidden" id="@((Model.Prefix + key).Replace(".", "__"))" name="@key" value="@this.Request[key].ToString()" />
        }
    }

    @foreach (var kvp in this.ViewContext.RouteData.Values)
    {
        if (kvp.Key == "controller" || kvp.Key == "action" || kvp.Key.ToString() == Model.Pager.Prefix + "CurrentPage" || kvp.Key.ToString() == "id")
        {
            continue;
        }

        <input type="hidden" id="@((Model.Prefix + kvp.Key).Replace(".", "__"))" name="@kvp.Key" value="@kvp.Value.ToString()" />
    }

    @foreach (var key in this.Request.Form.Keys)
    {
        if (filter.Count(f => Model.Prefix + f.Key.Name == key.ToString()) <= 0 && key.ToString() != Model.Pager.Prefix + "CurrentPage" && key.ToString() != "id")
        {
            <input type="hidden" id="@((Model.Prefix + key).Replace(".", "__"))" name="@key.ToString()" value="@this.Request.Form[key.ToString()].ToString()" />
        }
    }

    @foreach (KeyValuePair<PropertyInfo, FilterByAttribute> kvp in filter)
    {
        <label for="@(Model.Prefix.Replace(".", "__"))@kvp.Key.Name">@kvp.Value.DisplayName</label>
        <input class = "form-control" id="@(Model.Prefix.Replace(".", "__"))@kvp.Key.Name" type="text" name="@(Model.Prefix)@kvp.Key.Name" value="@kvp.Key.GetValue(Model, null)" />
    }
    <br/>
    <input class = "btn btn-default" type="submit" value="Filter" />   
</form>
<br />   